package intel

import (
	cpuid "github.com/u-root/cpuid"
)

// Based on arch/x86/include/asm/intel-family.h
// from the kernel codebase
const (
	INTEL_PENTIUM_PRO           = 0x01
	INTEL_PENTIUM_II_KLAMATH    = 0x03
	INTEL_PENTIUM_III_DESCHUTES = 0x05
	INTEL_PENTIUM_III_TUALATIN  = 0x0B
	INTEL_PENTIUM_M_DOTHAN      = 0x0D

	INTEL_CORE_YONAH = 0x0E

	INTEL_CORE2_MEROM      = 0x0F
	INTEL_CORE2_MEROM_L    = 0x16
	INTEL_CORE2_PENRYN     = 0x17
	INTEL_CORE2_DUNNINGTON = 0x1D

	INTEL_NEHALEM    = 0x1E
	INTEL_NEHALEM_G  = 0x1F
	INTEL_NEHALEM_EP = 0x1A
	INTEL_NEHALEM_EX = 0x2E

	INTEL_WESTMERE    = 0x25
	INTEL_WESTMERE_EP = 0x2C
	INTEL_WESTMERE_EX = 0x2F

	INTEL_SANDYBRIDGE   = 0x2A
	INTEL_SANDYBRIDGE_X = 0x2D
	INTEL_IVYBRIDGE     = 0x3A
	INTEL_IVYBRIDGE_X   = 0x3E

	INTEL_HASWELL   = 0x3C
	INTEL_HASWELL_X = 0x3F
	INTEL_HASWELL_L = 0x45
	INTEL_HASWELL_G = 0x46

	INTEL_BROADWELL   = 0x3D
	INTEL_BROADWELL_G = 0x47
	INTEL_BROADWELL_X = 0x4F
	INTEL_BROADWELL_D = 0x56

	INTEL_SKYLAKE_L = 0x4E
	INTEL_SKYLAKE   = 0x5E
	INTEL_SKYLAKE_X = 0x55

	INTEL_KABYLAKE_L = 0x8E
	INTEL_KABYLAKE   = 0x9E

	INTEL_COMETLAKE   = 0xA5
	INTEL_COMETLAKE_L = 0xA6

	INTEL_CANNONLAKE_L = 0x66

	INTEL_ICELAKE_X    = 0x6A
	INTEL_ICELAKE_D    = 0x6C
	INTEL_ICELAKE      = 0x7D
	INTEL_ICELAKE_L    = 0x7E
	INTEL_ICELAKE_NNPI = 0x9D

	INTEL_ROCKETLAKE = 0xA7

	INTEL_TIGERLAKE_L = 0x8C
	INTEL_TIGERLAKE   = 0x8D

	INTEL_SAPPHIRERAPIDS_X = 0x8F

	INTEL_EMERALDRAPIDS_X = 0xCF

	INTEL_GRANITERAPIDS_X = 0xAD
	INTEL_GRANITERAPIDS_D = 0xAE

	INTEL_BARTLETTLAKE = 0xD7

	// Hybrid processors

	INTEL_LAKEFIELD = 0x8A

	INTEL_ALDERLAKE   = 0x97
	INTEL_ALDERLAKE_L = 0x9A

	INTEL_RAPTORLAKE   = 0xB7
	INTEL_RAPTORLAKE_P = 0xBA
	INTEL_RAPTORLAKE_S = 0xBF

	INTEL_METEORLAKE   = 0xAC
	INTEL_METEORLAKE_L = 0xAA

	INTEL_ARROWLAKE_H = 0xC5
	INTEL_ARROWLAKE   = 0xC6
	INTEL_ARROWLAKE_U = 0xB5

	INTEL_LUNARLAKE_M = 0xBD

	INTEL_PANTHERLAKE_L = 0xCC
)

type BgVersion string

const (
	Unknown   BgVersion = "Unknown"
	Legacy    BgVersion = "Legacy (pre-Boot Guard)"
	BootGuard BgVersion = "Boot Guard (1.0)"
	CBnT20    BgVersion = "CBnT (2.0)"
	CBnT21    BgVersion = "CBnT (2.1)"
)

func bgVersion(model uint32) BgVersion {
	switch model {
	case INTEL_PENTIUM_PRO,
		INTEL_PENTIUM_II_KLAMATH,
		INTEL_PENTIUM_III_DESCHUTES,
		INTEL_PENTIUM_III_TUALATIN,
		INTEL_PENTIUM_M_DOTHAN,
		INTEL_CORE_YONAH,
		INTEL_CORE2_MEROM,
		INTEL_CORE2_MEROM_L,
		INTEL_CORE2_PENRYN,
		INTEL_CORE2_DUNNINGTON,
		INTEL_NEHALEM,
		INTEL_NEHALEM_G,
		INTEL_NEHALEM_EP,
		INTEL_NEHALEM_EX,
		INTEL_WESTMERE,
		INTEL_WESTMERE_EP,
		INTEL_WESTMERE_EX,
		INTEL_SANDYBRIDGE,
		INTEL_SANDYBRIDGE_X,
		INTEL_IVYBRIDGE,
		INTEL_IVYBRIDGE_X:
		return Legacy
	case INTEL_HASWELL,
		INTEL_HASWELL_X,
		INTEL_HASWELL_L,
		INTEL_HASWELL_G,
		INTEL_BROADWELL,
		INTEL_BROADWELL_G,
		INTEL_BROADWELL_X,
		INTEL_BROADWELL_D,
		INTEL_SKYLAKE_L,
		INTEL_SKYLAKE,
		INTEL_SKYLAKE_X,
		INTEL_KABYLAKE_L,
		INTEL_KABYLAKE,
		INTEL_COMETLAKE_L,
		INTEL_CANNONLAKE_L,
		INTEL_ICELAKE_X,
		INTEL_ICELAKE_D,
		INTEL_ICELAKE,
		INTEL_ICELAKE_L,
		INTEL_ICELAKE_NNPI,
		INTEL_LAKEFIELD:
		return BootGuard
	case INTEL_TIGERLAKE_L,
		INTEL_COMETLAKE,
		INTEL_ROCKETLAKE,
		INTEL_TIGERLAKE,
		INTEL_SAPPHIRERAPIDS_X,
		INTEL_EMERALDRAPIDS_X,
		INTEL_GRANITERAPIDS_X,
		INTEL_GRANITERAPIDS_D,
		INTEL_BARTLETTLAKE,
		INTEL_ALDERLAKE,
		INTEL_ALDERLAKE_L,
		INTEL_RAPTORLAKE,
		INTEL_RAPTORLAKE_P,
		INTEL_RAPTORLAKE_S:
		return CBnT20
	case INTEL_METEORLAKE,
		INTEL_METEORLAKE_L,
		INTEL_ARROWLAKE_H,
		INTEL_ARROWLAKE,
		INTEL_ARROWLAKE_U,
		INTEL_LUNARLAKE_M,
		INTEL_PANTHERLAKE_L:
		return CBnT21
	default:
		return Unknown
	}
}

func RuntimeBGVersion() BgVersion {
	return bgVersion(cpuid.DisplayModel)
}
